---
- hosts: all
  become: yes
  
  tasks:
  - name: Creating the users.
    user:
      name: "{{ item.name }}"
      password:  "{{ 'Abc$12345' | password_hash('sha512') }}"
      comment: "{{ item.comment }}"
      shell: /bin/bash
      group: tso
      groups: wheel
      home: /home/{{ item.name }}
    with_items:
      - { name: 'test1', comment: 'Test One' }
      - { name: 'test2', comment: 'Test Two' }
