---
- hosts: all
  become: yes
  vars:
    username: test2
    fullname: 'Test Two'

  tasks:
  - name: Creating the user {{ username }}
    user:
      name: "{{ username }}"
      password:  "{{ 'Abc$12345' | password_hash('sha512') }}"
      comment: "{{ fullname }}"
      shell: /bin/bash
      group: tso
      groups: wheel
      home: /home/{{ username }}
